endpoints:
  - name: test
    secrets:
      - test
    rules:
      - type: template
        destination: http://localhost:8081/webhook/hooks
        arguments:
          template: |
            { "test" : "{{ .test }}" }
  - name: hooks
    secrets:
      - hookSecret
    sources:
      - type: github
        arguments:
          secret: hookSecret
      - type: generic
        arguments:
          token: hookSecret
    rules:
      - type: display
        destination: http://localhost:8082
        arguments:
          template: |
            { "hook_executed": "{{ .test }}", "hook_secret": "{{ ._secrets.hookSecret }}" }
