endpoints:
  - name: test
    secret: test
    rules:
      - destination: http://localhost:8081/endpoint/test
        template: |
          my template
        verify_ssl: true
  - name: hooks
    secret: supersecret
