endpoints:
  - name: test
    secret: test
    rules:
      - type: template
        destination: http://localhost:8081/webhook/hooks
        arguments:
          template: |
            { "test" : "{{ .test }}" }
  - name: hooks
    secret: supersecret
    rules:
      - type: template
        destination: http://localhost:8082
        arguments:
          template: |
            { "hook_executed": "{{ .test }}" }
