endpoints:
  - name: test
    secret: test
    rules:
      - destination: |
          http://localhost:8081/endpoint 
        template: |
          my template
  - name: hooks
    secret: supersecret
