endpoints:
  - name: test
    secret: test
    rules:
      - destination: http://localhost:8081/webhook/hooks
        template: |
          { "test" : "{{ .test }}" }
  - name: hooks
    secret: supersecret
    rules:
      - destination: http://localhost:8082
        template: |
          { "hook_executed": "{{ .test }}" }
