endpoints:
  - name: test
    secrets:
      - test
    rules:
      - type: display
        echo: yes
        #destination: http://localhost:8081/webhook/hooks
        arguments:
          template: |
            {
              "test" : {{ multiply .test 10 }},
              "nestedData" : {{ .nestedData.innerTest }},
              "array":  {{ index .array 0 }}
            }


  - name: hooks
    secrets:
      - hookSecret
    sources:
      - type: github
        arguments:
          secret: hookToken
      - type: generic
        arguments:
          token: hookToken
    rules:
      - type: display
        echo: yes
        arguments:
          template: |
            { "hook_executed": "{{ .test }}", "hook_secret": "{{ ._secrets.hookSecret }}" }



  - name: Monzo2Ynab
    secrets:
      - ynabToken
      - budgetID
    headers:
      token: "{{ ._secrets.ynabToken }}"
      nonSecretToken: 12345
    sources:
      - type: generic
        arguments:
          token: hookToken
    rules:
      - type: display
        #destination: https://api.youneedabudget.com/v1/budgets/<ID>/transactions
        echo: yes
        arguments:
          template: |
            {
              "account_id": "{{ ._secrets.budgetID }}",
              "date": "{{ .data.created }}",
              "amount": {{ multiply .data.amount 10 }},
              "memo": "{{ .data.category }} : {{ .data.description }}",
              "payee_name": "{{ .data.merchant.name }}"
            }
