endpoints:
  - name: test
    secrets:
      - test
    rules:
      - type: template
        destination: http://localhost:8081/webhook/hooks
        arguments:
          template: |
            { "test" : "{{ .test }}" }
  - name: hooks
    secrets:
      - hookSecret
    sources:
      - type: github
        arguments:
          secret: hookToken
      - type: generic
        arguments:
          token: hookToken
    rules:
      - type: display
        echo: yes
        arguments:
          template: |
            { "hook_executed": "{{ .test }}", "hook_secret": "{{ ._secrets.hookSecret }}" }
  - name: Monzo2Ynab
    secrets:
      - ynabToken
      - budgetID
    sources:
      - type: generic
        arguments:
          token: hookToken
    rules:
      - type: template
        destination: https://api.youneedabudget.com/v1/budgets/<ID>/transactions
        arguments:
          template: |
            {
              "account_id": "{{ ._secrets.budgetID }}",
              "date": "{{ .date.created }}",
              "amount": "{{ multiply .data.amount 10 }}",
              "memo": "{{ .data.category }} : {{ .data.description }}",
              payee_name: "{{ .data.merchant }}"
            }